### ISSUE TITLE
"Target directory is not within the Quake basedir" Arch

### ISSUE THREAD

**Issue by SkrimbleBuff** [neogeographica/singleplayer_scripts#31]
I really like the project, but can't seem to configure it correctly.
My Quake installation (id1, game dirs) is mounted on:
`/mnt/gam/GameLibrary_Other/Quake/`
_(My user account owns the folder and has 777 access)_

I do not want to use a userdata directory outside of the standard Quake directory.
My quakelaunch.conf looks like this:

```
basedir="/mnt/gam/GameLibrary_Other/Quake/"
quake="/usr/bin/quakespasm"
#quake_args="some arguments here"
#userdata_home="/mnt/gam/GameLibrary_Other/Quake"
install_to_userdata=false
#shortcuts_dir="/path/to/some/directory"
cleanup_archive=true
keep_basedir_subdirectory_on_cleanup=false
#keep_userdata_subdirectory_on_cleanup=false
[...]
```

If I right-click a zip file or a gamedir folder and choose "Open With > Quake", i always get the message **"Target directory is not within the Quake basedir"**. I tried everything, including using userdata directories to no avail. I am not sure I am just misunderstanding some setting. Would really love to get this to work!

**System:**
Arch Linux x64
6.1.14-1-lts
XFCE-4

**Comment by neogeographica** [comment]
Thanks for the report! I don't have an Arch environment handy at the moment but when I get a free moment I will at least do some re-reading of the relevant codepaths.

**Comment by neogeographica** [comment]
Actually one quick suggestion first, try removing the trailing slash from basedir. For whatever reason (I'm sure just some substring comparison that is not super-robust) I can recreate your error if I put a trailing slash on that path value.

Will probably just reveal the next issue :-) but worth a try.

**Comment by neogeographica** [comment]
Going to close this since I believe that identifies the issue and solution. Re-open if not!
